version: "3.9"

services:
  db:
    image: postgres:15
    container_name: db_pg
    volumes:
      - ~/.pg/pg_data/wallet:/var/lib/postgresql/pg_data
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 10s
      retries: 3
  web:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: DRF-API
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    command: >
      bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py initadmin && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    restart: always
